### ISSUE TITLE
src code missing?

### ISSUE THREAD

**Issue by ofields** [adizanni/ExportToHASS#2]

**Comment by ofields** [comment]
The sh3p file is really a zip file -> in there is the src code along with the compiles java classes

**Comment by adizanni** [comment]
Hello ofields, I have decided to keep the source code secret because the pluging is in a very early stage and I prefer to avoid forks of a code that is still in a very bad shape. Bu the end of August, regardless if I manage to  tidy up the code
 I will make it open. Promised
